const types = {
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  UI_TOGGLE_LOGGING: 'UI_TOGGLE_LOGGING',
  UI_TOGGLE_REGISTERING: 'UI_TOGGLE_REGISTERING',
  UI_TOGGLE_GETTING_BALANCE: 'UI_TOGGLE_GETTING_BALANCE',
  UI_TOGGLE_ADDING_OPERATION: 'UI_TOGGLE_ADDING_OPERATION',
  UI_TOGGLE_REMOVING_OPERATION: 'UI_TOGGLE_REMOVING_OPERATION',
  UI_TOGGLE_UPDATING_OPERATION: 'UI_TOGGLE_UPDATING_OPERATION',
  OPERATION_LOAD_BALANCE: 'OPERATION_LOAD_BALANCE',
  OPERATION_LOAD_OPERATIONS: 'OPERATION_LOAD_OPERATIONS',
  OPERATION_LOAD_CATEGORIES: 'OPERATION_LOAD_CATEGORIES',
  OPERATION_CHANGE_MODE_ADD: 'OPERATION_CHANGE_MODE_ADD',
  OPERATION_CHANGE_MODE_SUBTRACT: 'OPERATION_CHANGE_MODE_SUBTRACT',
  OPERATION_CHANGE_MODE_UP: 'OPERATION_CHANGE_MODE_UP',
  OPERATION_CHANGE_MODE_OFF: 'OPERATION_CHANGE_MODE_OFF',
  OPERATION_MAKE_OPERATION: 'OPERATION_MAKE_OPERATION',
  OPERATION_REMOVE_OPERATION: 'OPERATION_REMOVE_OPERATION',
  OPERATION_UPDATE_OPERATION: 'OPERATION_UPDATE_OPERATION',
};

export default types;
