const types = {
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  UI_TOGGLE_LOGGING: 'UI_TOGGLE_LOGGING',
  UI_TOGGLE_REGISTERING: 'UI_TOGGLE_REGISTERING',
  UI_TOGGLE_GETTING_BALANCE: 'UI_TOGGLE_GETTING_BALANCE',
  OPERATION_LOAD_BALANCE: 'OPERATION_LOAD_BALANCE',
  OPERATION_LOAD_OPERATIONS: 'OPERATION_LOAD_OPERATIONS',
  OPERATION_LOAD_CATEGORIES: 'OPERATION_LOAD_CATEGORIES',
};

export default types;
